# Generated by Django 2.2.12 on 2020-09-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type_of_service', models.CharField(choices=[('B', 'Business'), ('C', 'Couples'), ('S', 'Solo travel'), ('F', 'Family'), ('G', "Friend's gateway")], default='B', max_length=1)),
            ],
        ),
    ]
